import {
  DEFAULT_MODEL_SERVER_ACTIVE_DECODE_STEPS_PER_PREFILL_CHUNK,
  DEFAULT_MODEL_SERVER_ACTIVE_PREFILL_STEP_SIZE,
  DEFAULT_MODEL_SERVER_BATCH_WINDOW_MS,
  DEFAULT_MODEL_SERVER_GPU_MEMORY_UTILIZATION,
  DEFAULT_MODEL_SERVER_HOSTNAME,
  DEFAULT_MODEL_SERVER_MAX_BATCH_SIZE,
  DEFAULT_MODEL_SERVER_MAX_CONCURRENT_REQUESTS,
  DEFAULT_MODEL_SERVER_MAX_GENERATED_TOKENS,
  DEFAULT_MODEL_SERVER_MAX_PROMPT_TOKENS,
  DEFAULT_MODEL_SERVER_MAX_TOTAL_TOKENS,
  DEFAULT_MODEL_SERVER_PORT,
  DEFAULT_MODEL_SERVER_PREFILL_STEP_SIZE,
  DEFAULT_MODEL_SERVER_PROMPT_PREFIX_CACHE_MAX_ENTRIES,
  DEFAULT_MODEL_SERVER_STREAM_DECODE_INTERVAL,
} from "./model-loading/server";

export function formatServeUsage(): string {
  return [
    "Serve one or more local or Hugging Face models through the @mlxts/serve OpenAI-compatible API.",
    "",
    "Usage:",
    "  mlxts-serve <model-path-or-repo-id> [options]",
    "  mlxts-serve --model <model-path-or-repo-id> [--model <model-id=path-or-repo-id>] [options]",
    "  mlxts-serve --model-root <directory> [--model-root <directory>] [options]",
    "  mlxts-serve discover --model-root <directory> [--full]",
    "  bunx @mlxts/serve <model-path-or-repo-id> [options]",
    "",
    "Options:",
    "  --model <source|id=source>  Add a model source; repeat for multi-model serving",
    "  --model-root <directory>    Discover supported autoregressive checkpoints under root and org/model folders",
    "  --model-load-policy <eager|lazy>  Load all models at startup or on first request",
    "  --model-idle-ttl-ms <n>     Evict lazy-loaded idle models after n milliseconds",
    "  --pin-model <id>            Keep a lazy-loaded model resident; repeat as needed",
    "  --model-id <id>             Served model id for positional single-model usage",
    "  --served-model-name <id>    Alias for --model-id",
    `  --host <host>               Hostname to bind (default: ${DEFAULT_MODEL_SERVER_HOSTNAME})`,
    `  --port <port>               Port to bind (default: ${DEFAULT_MODEL_SERVER_PORT})`,
    `  --max-generated-tokens <n>  Reject requests above this max_tokens cap (default: ${DEFAULT_MODEL_SERVER_MAX_GENERATED_TOKENS})`,
    `  --max-prompt-tokens <n>     Reject prompts above this tokenized prompt cap (default: ${DEFAULT_MODEL_SERVER_MAX_PROMPT_TOKENS})`,
    `  --max-total-tokens <n>      Reject prompt_tokens + max_tokens above this cap (default: ${DEFAULT_MODEL_SERVER_MAX_TOTAL_TOKENS})`,
    `  --max-batch-size <n>        Admission micro-batch size per model instance (default: ${DEFAULT_MODEL_SERVER_MAX_BATCH_SIZE})`,
    `  --batch-window-ms <n>       Wait window before flushing a micro-batch (default: ${DEFAULT_MODEL_SERVER_BATCH_WINDOW_MS})`,
    `  --prefill-step-size <n>     Cold prompt-prefill chunk size (default: ${DEFAULT_MODEL_SERVER_PREFILL_STEP_SIZE})`,
    [
      "  --active-prefill-step-size <n>",
      `Prompt-prefill chunk size while rows are decoding (default: ${DEFAULT_MODEL_SERVER_ACTIVE_PREFILL_STEP_SIZE})`,
    ].join("  "),
    [
      "  --active-decode-steps-per-prefill-chunk <n>",
      `Decode-step quantum before long prompt-prefill work resumes (default: ${DEFAULT_MODEL_SERVER_ACTIVE_DECODE_STEPS_PER_PREFILL_CHUNK})`,
    ].join("  "),
    `  --stream-decode-interval <n>  Decode/flush streaming text every n generated token(s) (default: ${DEFAULT_MODEL_SERVER_STREAM_DECODE_INTERVAL})`,
    `  --max-concurrent-requests <n>  Max in-flight jobs per served model (default: ${DEFAULT_MODEL_SERVER_MAX_CONCURRENT_REQUESTS})`,
    `  --prompt-prefix-cache-max-entries <n>  Retained prompt-prefix snapshots per served model (default: ${DEFAULT_MODEL_SERVER_PROMPT_PREFIX_CACHE_MAX_ENTRIES})`,
    "  --prompt-prefix-cache-max-bytes <n>  Estimated retained prompt-prefix snapshot bytes per served model",
    `  --gpu-memory-utilization <f>   Reject estimated requests above this fraction of MLX memory limit (default: ${DEFAULT_MODEL_SERVER_GPU_MEMORY_UTILIZATION})`,
    "  --remote-image-host <host>      Allow remote image URLs from this exact host; repeat for redirects/CDNs",
    "  --revision <ref>            Hugging Face revision when source is a repo id",
    "  --access-token <token>      Hugging Face access token for private or gated repos",
    "  --cache-dir <path>          Hugging Face cache directory",
    "  --api-key <key>             Require Authorization: Bearer <key> for /v1 routes",
    "  --local-files-only          Use only already-cached/local files",
    "  --verbose                   Log request and generation lifecycle events",
    "  --help                      Show this help",
  ].join("\n");
}
