export const TRACKED_TENSOR_PRODUCING_CALL_NAMES = [
  "abs",
  "add",
  "arange",
  "asType",
  "astype",
  "array",
  "bernoulli",
  "broadcastTo",
  "categorical",
  "concatenate",
  "crossEntropy",
  "divide",
  "equal",
  "expandDims",
  "exp",
  "flatten",
  "fromData",
  "full",
  "gelu",
  "greater",
  "greaterEqual",
  "key",
  "less",
  "lessEqual",
  "log",
  "logsumexp",
  "matmul",
  "maximum",
  "mean",
  "minimum",
  "multiply",
  "negative",
  "notEqual",
  "normal",
  "ones",
  "power",
  "reciprocal",
  "relu",
  "reshape",
  "scaledDotProductAttention",
  "sigmoid",
  "silu",
  "softmax",
  "split",
  "sqrt",
  "square",
  "stack",
  "stopGradient",
  "subtract",
  "sum",
  "takeAlongAxis",
  "takeAxis",
  "tanh",
  "transpose",
  "tril",
  "triu",
  "uniform",
  "where",
  "zeros",
] as const;

export type TrackedTensorProducingCallName = (typeof TRACKED_TENSOR_PRODUCING_CALL_NAMES)[number];

const trackedTensorProducingCallNameSet = new Set<string>(TRACKED_TENSOR_PRODUCING_CALL_NAMES);

export function isTrackedTensorProducingCallName(
  name: string,
): name is TrackedTensorProducingCallName {
  return trackedTensorProducingCallNameSet.has(name);
}
