export const TRACKED_TENSOR_PRODUCING_CALL_NAMES = [
  "abs",
  "add",
  "arange",
  "asType",
  "astype",
  "array",
  "bernoulli",
  "broadcastTo",
  "categorical",
  "concatenate",
  "crossEntropy",
  "divide",
  "equal",
  "erf",
  "expandDims",
  "exp",
  "flatten",
  "fastLayerNorm",
  "fastRoPE",
  "fastRmsNorm",
  "fromData",
  "full",
  "gelu",
  "geluApprox",
  "greater",
  "greaterEqual",
  "key",
  "less",
  "lessEqual",
  "log",
  "logsumexp",
  "max",
  "matmul",
  "min",
  "maximum",
  "mean",
  "minimum",
  "multiply",
  "negative",
  "notEqual",
  "normal",
  "ones",
  "power",
  "putAlongAxis",
  "reciprocal",
  "repeat",
  "relu",
  "reshape",
  "rmsNorm",
  "rope",
  "scaledDotProductAttention",
  "sigmoid",
  "silu",
  "slice",
  "sliceDynamic",
  "sliceUpdate",
  "sliceUpdateDynamic",
  "softmax",
  "sort",
  "split",
  "sqrt",
  "squeeze",
  "square",
  "stack",
  "stopGradient",
  "subtract",
  "sum",
  "swiglu",
  "takeAlongAxis",
  "takeAxis",
  "tanh",
  "tile",
  "topk",
  "transpose",
  "tril",
  "triu",
  "uniform",
  "where",
  "zeros",
  "argmax",
  "argmin",
  "argpartition",
  "argsort",
  "cumsum",
  "retainArray",
] as const;

export type TrackedTensorProducingCallName = (typeof TRACKED_TENSOR_PRODUCING_CALL_NAMES)[number];

const trackedTensorProducingCallNameSet = new Set<string>(TRACKED_TENSOR_PRODUCING_CALL_NAMES);

export function isTrackedTensorProducingCallName(
  name: string,
): name is TrackedTensorProducingCallName {
  return trackedTensorProducingCallNameSet.has(name);
}
